### ISSUE TITLE
Add a no-op pipe_t?

### ISSUE THREAD

**Issue by tengjiang** [comse6998/spring2024#133]
Currently, the pipe() by default returns pipes::FXArith;
It seems a little weird to default to pipes::FXArith, and it makes it a little hard to distinguish between a wrong/undefined/no-op operation encoding and pipes::FXArith. So it might be a good idea to include a NOP to pipe_t.

**Comment by tengjiang** [comment]
If we want to be strict about error checking, we can even add an UNDEFINED type and throw an error every time we encounter one.

**Comment by joseemoreira** [comment]
I agree with the idea to include a nop to pipe_t. You can go ahead.

**Comment by tengjiang** [comment]
Hello professor: I'll create the PR once the basic implementation for FP is merged. This observation actually helped me to solve the infinite loop problem, and I will address it in the corresponding PR.
