### ISSUE TITLE
Issues with FX pipeline

### ISSUE THREAD

**Issue by tengjiang** [comse6998/spring2024#139]
Hello FX pipeline implementers: I've discovered some issues I'm not fully understanding in your implementation:
* in IQstage::tick(): (This applies to all 3 cases), shouldn't the last line be  `FX[_ix].pipe_traffic += 0x10;`  ?
```c++
...
case CDC8600::pipes::FXArith: 	if((FX[_ix].pipe_traffic & 0x10) == 0)
	{
		copy(96, opsq[i], 0, out, 0);	// copy operation i to output
		opsq.erase(opsq.begin() + i);	// dequeue operation i
		FX->pipe_traffic += 0x10; // Shouldn't this be 'FX[_ix].pipe_traffic += 0x10;'  ?

	} 
...
``` 
* in FXstage::tick(): I feel that `pipe_traffic` should shift` pipe_traffic = pipe_traffic << 1;` no matter whether `txdone && rxdone`

**Comment by lafis002** [comment]
Hi, the first point is fixed, with the second point i disagree, because the transfer between the stages only happens when txdone and rxdone are true, shifting the pipetraffic without shifting the actual pipe would be incorrect in my opinion.

**Comment by tengjiang** [comment]
Yep, you are right!
