### ISSUE TITLE
Registers seem not to be released

### ISSUE THREAD

**Issue by lafis002** [comse6998/spring2024#155]
With the newest commits, the pfind function fails very early on.

Error: 

Assertion failed: (lrutime < UINT64_MAX), function pfind, file CDC8600.cc, line 264.
Abort trap: 6

Before the latest commits I only got that for some traces later in the program and increasing the available registers fixed the problem, now it does not fix it anymore, one of the newest changes must have a bug regarding the register claiming and freeing process.

**Comment by joseemoreira** [comment]
I made another commit yesterday afternoon. That fixed the problem for `dcopy`. Are you still having it with `dger`?

**Comment by lafis002** [comment]
The issue with the registers seems to be fixed. Now we are stuck in the infinite loop :D
