### ISSUE TITLE
BB instruction gets stuck in pipe

### ISSUE THREAD

**Issue by lafis002** [comse6998/spring2024#167]
Every trace that contains bb results in an endless loop. Maybe it is the combination of branch instruction and 16 bit instruction, because all other branch instructions are 32 bit.

**Comment by joseemoreira** [comment]
The bb instruction is cracked into two operations: cmp and bb. The cmp operation was getting stuck because no mapper for it was defined. That has been fixed. Please see if your tests pass.

**Comment by lafis002** [comment]
Ah perfect, thank you. I only checked the bb instruction and forgot that it cracks into cmp and bb. Now everything passes for me.
